"""Constants package for OMRChecker.

This package contains all extracted constants organized by category:
- image_processing: Image processing and CV constants
- display: UI and display-related constants
- file_operations: File handling constants
"""

# Import all image processing constants for easy access
from src.constants.image_processing import (
    # Measurements
    ALLOWED_DISTANCE_ERROR_PERCENTAGE,
    APPROX_POLY_EPSILON_FACTOR,
    AUTO_CANNY_SIGMA_DEFAULT,
    CANNY_THRESHOLD_HIGH,
    CANNY_THRESHOLD_LOW,
    # Image quality
    CLAHE_CLIP_LIMIT,
    CLAHE_TILE_GRID_SIZE,
    COLOR_BLACK,
    COLOR_BLUE,
    COLOR_GREEN,
    COLOR_RED,
    COLOR_WHITE,
    CONTOUR_THICKNESS_STANDARD,
    CV2_CONTOURS_LENGTH_V2,
    CV2_CONTOURS_LENGTH_V3,
    DECIMAL_PLACES_RATE,
    DECIMAL_PLACES_TIME,
    DEFAULT_IMAGES_PER_ROW,
    DEFAULT_IMAGES_PER_ROW_HIGH_DETAIL,
    DISPLAY_LEVEL_DEBUG,
    DISPLAY_LEVEL_ERROR_ONLY,
    DISPLAY_LEVEL_HIGH,
    DISPLAY_LEVEL_NONE,
    GAUSSIAN_BLUR_KERNEL_DEFAULT,
    GAUSSIAN_BLUR_SIGMA,
    # Marker detection
    MARKER_MATCH_MIN_THRESHOLD_DEFAULT,
    MARKER_RESCALE_RANGE_MAX_DEFAULT,
    MARKER_RESCALE_RANGE_MIN_DEFAULT,
    MARKER_RESCALE_STEPS_DEFAULT,
    MIN_ALLOWED_CONTROL_POINTS,
    MIN_MARKER_AREA,
    # Areas and sizes
    MIN_PAGE_AREA,
    MORPH_ITERATIONS_DOT_OPEN,
    MORPH_ITERATIONS_STANDARD,
    # Morphological operations
    MORPH_KERNEL_DEFAULT,
    MORPH_KERNEL_LARGE,
    MORPH_KERNEL_SMALL,
    NORMALIZE_ALPHA_DEFAULT,
    NORMALIZE_BETA_DEFAULT,
    PADDING_MULTIPLIER_KERNEL,
    PAPER_SATURATION_THRESHOLD,
    # Paper detection
    PAPER_VALUE_THRESHOLD,
    # Pixel values
    PIXEL_VALUE_MAX,
    PIXEL_VALUE_MID,
    PIXEL_VALUE_MIN,
    RECTANGLE_CORNERS_COUNT,
    SECONDS_PER_MINUTE,
    # Statistics
    STATS_LABEL_WIDTH,
    THRESH_DOT_DEFAULT,
    # Thresholds
    THRESH_PAGE_TRUNCATE_HIGH,
    THRESH_PAGE_TRUNCATE_SECONDARY,
    # Collections
    TOP_CONTOURS_COUNT,
    # Display
    TRANSPARENCY_OVERLAY_DEFAULT,
    WHITE_PADDING_VALUE,
)

__all__ = [
    # Measurements
    "ALLOWED_DISTANCE_ERROR_PERCENTAGE",
    "APPROX_POLY_EPSILON_FACTOR",
    "AUTO_CANNY_SIGMA_DEFAULT",
    "CANNY_THRESHOLD_HIGH",
    "CANNY_THRESHOLD_LOW",
    # Image quality
    "CLAHE_CLIP_LIMIT",
    "CLAHE_TILE_GRID_SIZE",
    "COLOR_BLACK",
    "COLOR_BLUE",
    "COLOR_GREEN",
    "COLOR_RED",
    "COLOR_WHITE",
    "CONTOUR_THICKNESS_STANDARD",
    "CV2_CONTOURS_LENGTH_V2",
    "CV2_CONTOURS_LENGTH_V3",
    "DECIMAL_PLACES_RATE",
    "DECIMAL_PLACES_TIME",
    "DEFAULT_IMAGES_PER_ROW",
    "DEFAULT_IMAGES_PER_ROW_HIGH_DETAIL",
    "DISPLAY_LEVEL_DEBUG",
    "DISPLAY_LEVEL_ERROR_ONLY",
    "DISPLAY_LEVEL_HIGH",
    "DISPLAY_LEVEL_NONE",
    "GAUSSIAN_BLUR_KERNEL_DEFAULT",
    "GAUSSIAN_BLUR_SIGMA",
    # Marker detection
    "MARKER_MATCH_MIN_THRESHOLD_DEFAULT",
    "MARKER_RESCALE_RANGE_MAX_DEFAULT",
    "MARKER_RESCALE_RANGE_MIN_DEFAULT",
    "MARKER_RESCALE_STEPS_DEFAULT",
    "MIN_ALLOWED_CONTROL_POINTS",
    "MIN_MARKER_AREA",
    # Areas and sizes
    "MIN_PAGE_AREA",
    "MORPH_ITERATIONS_DOT_OPEN",
    "MORPH_ITERATIONS_STANDARD",
    # Morphological operations
    "MORPH_KERNEL_DEFAULT",
    "MORPH_KERNEL_LARGE",
    "MORPH_KERNEL_SMALL",
    "NORMALIZE_ALPHA_DEFAULT",
    "NORMALIZE_BETA_DEFAULT",
    "PADDING_MULTIPLIER_KERNEL",
    "PAPER_SATURATION_THRESHOLD",
    # Paper detection
    "PAPER_VALUE_THRESHOLD",
    # Pixel values
    "PIXEL_VALUE_MAX",
    "PIXEL_VALUE_MID",
    "PIXEL_VALUE_MIN",
    "RECTANGLE_CORNERS_COUNT",
    "SECONDS_PER_MINUTE",
    # Statistics
    "STATS_LABEL_WIDTH",
    "THRESH_DOT_DEFAULT",
    # Thresholds
    "THRESH_PAGE_TRUNCATE_HIGH",
    "THRESH_PAGE_TRUNCATE_SECONDARY",
    # Collections
    "TOP_CONTOURS_COUNT",
    # Display
    "TRANSPARENCY_OVERLAY_DEFAULT",
    "WHITE_PADDING_VALUE",
]
